version: "3.7"
services:
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - bridge
volumes:
  mysqldata: